#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python -m pip install --upgrade pip

pipx install poetry

poetry self add poetry-plugin-export
poetry config warnings.export false
poetry config virtualenvs.in-project true
poetry completions bash >> ~/.bash_completion
poetry install
